//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBRequest.h"

@class NSMutableArray, NSString;

@interface ALSLocationRequest : PBRequest
{
    NSString *_appBundleId;
    NSMutableArray *_cdmaCellTowers;
    NSMutableArray *_cdmaEvdoTowers;
    NSMutableArray *_cellTowers;
    NSMutableArray *_lteCellTowers;
    int _numberOfSurroundingCdmaCells;
    int _numberOfSurroundingCdmaEvdoCells;
    int _numberOfSurroundingCells;
    int _numberOfSurroundingLteCells;
    int _numberOfSurroundingScdmaCells;
    int _numberOfSurroundingWifis;
    NSMutableArray *_scdmaCellTowers;
    NSMutableArray *_wirelessAPs;
    struct {
        unsigned int numberOfSurroundingCdmaCells:1;
        unsigned int numberOfSurroundingCdmaEvdoCells:1;
        unsigned int numberOfSurroundingCells:1;
        unsigned int numberOfSurroundingLteCells:1;
        unsigned int numberOfSurroundingScdmaCells:1;
        unsigned int numberOfSurroundingWifis:1;
    } _has;
}

@property(nonatomic) int numberOfSurroundingScdmaCells; // @synthesize numberOfSurroundingScdmaCells=_numberOfSurroundingScdmaCells;
@property(retain, nonatomic) NSMutableArray *scdmaCellTowers; // @synthesize scdmaCellTowers=_scdmaCellTowers;
@property(nonatomic) int numberOfSurroundingLteCells; // @synthesize numberOfSurroundingLteCells=_numberOfSurroundingLteCells;
@property(retain, nonatomic) NSMutableArray *lteCellTowers; // @synthesize lteCellTowers=_lteCellTowers;
@property(nonatomic) int numberOfSurroundingCdmaEvdoCells; // @synthesize numberOfSurroundingCdmaEvdoCells=_numberOfSurroundingCdmaEvdoCells;
@property(nonatomic) int numberOfSurroundingCdmaCells; // @synthesize numberOfSurroundingCdmaCells=_numberOfSurroundingCdmaCells;
@property(retain, nonatomic) NSMutableArray *cdmaEvdoTowers; // @synthesize cdmaEvdoTowers=_cdmaEvdoTowers;
@property(retain, nonatomic) NSMutableArray *cdmaCellTowers; // @synthesize cdmaCellTowers=_cdmaCellTowers;
@property(retain, nonatomic) NSString *appBundleId; // @synthesize appBundleId=_appBundleId;
@property(nonatomic) int numberOfSurroundingWifis; // @synthesize numberOfSurroundingWifis=_numberOfSurroundingWifis;
@property(nonatomic) int numberOfSurroundingCells; // @synthesize numberOfSurroundingCells=_numberOfSurroundingCells;
@property(retain, nonatomic) NSMutableArray *wirelessAPs; // @synthesize wirelessAPs=_wirelessAPs;
@property(retain, nonatomic) NSMutableArray *cellTowers; // @synthesize cellTowers=_cellTowers;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)copyTo:(id)arg1;
- (Class)responseClass;
- (unsigned int)requestTypeCode;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) BOOL hasNumberOfSurroundingScdmaCells;
- (id)scdmaCellTowerAtIndex:(unsigned int)arg1;
- (unsigned int)scdmaCellTowersCount;
- (void)addScdmaCellTower:(id)arg1;
- (void)clearScdmaCellTowers;
@property(nonatomic) BOOL hasNumberOfSurroundingLteCells;
- (id)lteCellTowerAtIndex:(unsigned int)arg1;
- (unsigned int)lteCellTowersCount;
- (void)addLteCellTower:(id)arg1;
- (void)clearLteCellTowers;
@property(nonatomic) BOOL hasNumberOfSurroundingCdmaEvdoCells;
@property(nonatomic) BOOL hasNumberOfSurroundingCdmaCells;
- (id)cdmaEvdoTowerAtIndex:(unsigned int)arg1;
- (unsigned int)cdmaEvdoTowersCount;
- (void)addCdmaEvdoTower:(id)arg1;
- (void)clearCdmaEvdoTowers;
- (id)cdmaCellTowerAtIndex:(unsigned int)arg1;
- (unsigned int)cdmaCellTowersCount;
- (void)addCdmaCellTower:(id)arg1;
- (void)clearCdmaCellTowers;
@property(readonly, nonatomic) BOOL hasAppBundleId;
@property(nonatomic) BOOL hasNumberOfSurroundingWifis;
@property(nonatomic) BOOL hasNumberOfSurroundingCells;
- (id)wirelessAPAtIndex:(unsigned int)arg1;
- (unsigned int)wirelessAPsCount;
- (void)addWirelessAP:(id)arg1;
- (void)clearWirelessAPs;
- (id)cellTowerAtIndex:(unsigned int)arg1;
- (unsigned int)cellTowersCount;
- (void)addCellTower:(id)arg1;
- (void)clearCellTowers;
- (void)dealloc;

@end

