//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

@interface ALSLocation : PBCodable
{
    long long _latitude;
    long long _longitude;
    int _accuracy;
    int _altitude;
    int _confidence;
    unsigned int _infoMask;
    int _locationType;
    int _reach;
    unsigned int _score;
    int _verticalAccuracy;
    struct {
        unsigned int altitude:1;
        unsigned int confidence:1;
        unsigned int infoMask:1;
        unsigned int locationType:1;
        unsigned int reach:1;
        unsigned int score:1;
        unsigned int verticalAccuracy:1;
    } _has;
}

@property(nonatomic) unsigned int infoMask; // @synthesize infoMask=_infoMask;
@property(nonatomic) int reach; // @synthesize reach=_reach;
@property(nonatomic) unsigned int score; // @synthesize score=_score;
@property(nonatomic) int confidence; // @synthesize confidence=_confidence;
@property(nonatomic) int verticalAccuracy; // @synthesize verticalAccuracy=_verticalAccuracy;
@property(nonatomic) int altitude; // @synthesize altitude=_altitude;
@property(nonatomic) int locationType; // @synthesize locationType=_locationType;
@property(nonatomic) int accuracy; // @synthesize accuracy=_accuracy;
@property(nonatomic) long long longitude; // @synthesize longitude=_longitude;
@property(nonatomic) long long latitude; // @synthesize latitude=_latitude;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) BOOL hasInfoMask;
@property(nonatomic) BOOL hasReach;
@property(nonatomic) BOOL hasScore;
@property(nonatomic) BOOL hasConfidence;
@property(nonatomic) BOOL hasVerticalAccuracy;
@property(nonatomic) BOOL hasAltitude;
@property(nonatomic) BOOL hasLocationType;
- (void)dealloc;

@end

