//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBRequester.h"

@interface CLALSRequester : PBRequester
{
    int tag;
    int type;
    double timestamp;
    BOOL processingCellTowers;
    BOOL processingWirelessAPs;
    BOOL finished;
}

@property BOOL finished; // @synthesize finished;
@property BOOL processingWirelessAPs; // @synthesize processingWirelessAPs;
@property BOOL processingCellTowers; // @synthesize processingCellTowers;
@property double timestamp; // @synthesize timestamp;
@property int type; // @synthesize type;
@property int tag; // @synthesize tag;

@end

