//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLLocationProviderProtocol.h"

@interface CLLocationProviderAdapter : CLNotifierServiceAdapter <CLLocationProviderProtocol>
{
}

- (void)setSimulationEnabled:(BOOL)arg1;
- (void)shutdown;
- (void)start;
- (void)register:(byref id)arg1 forNotification:(int)arg2 distanceFilter:(double)arg3;
- (void)updateNotification:(int)arg1 withRegistrationInfo:(id)arg2 forClient:(byref id)arg3;
- (struct CLLocationProvider *)locationProvider;

@end

