//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLIntersiloService.h"

#import "CLLocationHarvesterProtocol.h"

@interface CLLocationHarvesterAdapter : CLIntersiloService <CLLocationHarvesterProtocol>
{
    struct CLLocationHarvester *_harvester;
}

+ (id)getSilo;
@property(nonatomic) struct CLLocationHarvester *harvester; // @synthesize harvester=_harvester;
- (void)shutdown;
- (void)setHarvestingEnabled:(BOOL)arg1;
- (void)setPrivateMode:(BOOL)arg1;
- (void)endService;
- (void)beginService;
- (id)initInSilo:(id)arg1;
- (void)heartAttack;

@end

