//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLIntersiloServiceProtocol.h"

@class CLLocation;

@protocol CLRoutineMonitorServiceProtocol <CLIntersiloServiceProtocol>
- (void)fetchLocationsOfInterestWithinDistance:(double)arg1 ofLocation:(CLLocation *)arg2 withReply:(void (^)(NSArray *, NSError *))arg3;
- (void)fetchRoutineModeFromLocation:(CLLocation *)arg1 withReply:(void (^)(int, NSError *))arg2;
@end

