//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLIntersiloService.h"

#import "CLLocationManagerRoutineServerInterface.h"
#import "CLRoutineMonitorServiceProtocol.h"
#import "NSXPCListenerDelegate.h"

@class NSMutableArray, NSObject<OS_dispatch_source>, NSXPCConnection, NSXPCListener, RTRoutineManager;

@interface CLRoutineMonitor : CLIntersiloService <NSXPCListenerDelegate, CLLocationManagerRoutineServerInterface, CLRoutineMonitorServiceProtocol>
{
    NSObject<OS_dispatch_source> *_wakeRoutinedTimer;
    struct CLServiceLocationProvider *_serviceLocationProvider;
    struct unique_ptr<CLServiceLocationProvider_Type::Client, std::__1::default_delete<CLServiceLocationProvider_Type::Client>> _serviceLocationClient;
    struct unique_ptr<CLClientManager_Type::Client, std::__1::default_delete<CLClientManager_Type::Client>> _clientManagerClient;
    BOOL _updating;
    BOOL _authorized;
    BOOL _armed;
    NSXPCConnection *_connection;
    NSMutableArray *_locations;
    NSXPCListener *_listener;
    RTRoutineManager *_routineManager;
}

+ (id)getSilo;
@property(retain, nonatomic) RTRoutineManager *routineManager; // @synthesize routineManager=_routineManager;
@property(nonatomic) BOOL armed; // @synthesize armed=_armed;
@property(nonatomic) BOOL authorized; // @synthesize authorized=_authorized;
@property(nonatomic) BOOL updating; // @synthesize updating=_updating;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
@property(retain, nonatomic) NSMutableArray *locations; // @synthesize locations=_locations;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onWakeRoutinedTimer;
- (void)stopWakeRoutinedTimer;
- (void)startWakeRoutinedTimer;
- (void)sendLocations;
- (void)stopUpdatingLocation;
- (void)startUpdatingLocation;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)checkAuthorization;
- (void)flush;
- (void)onLocationNotification:(int)arg1 data:(NotificationData_522b5f94)arg2;
- (void)onClientManagerNotification:(int)arg1 data:(struct NotificationData)arg2;
- (void)addLocation:(id)arg1;
- (void)dealloc;
- (void)fetchLocationsOfInterestWithinDistance:(double)arg1 ofLocation:(id)arg2 withReply:(CDUnknownBlockType)arg3;
- (void)fetchRoutineModeFromLocation:(id)arg1 withReply:(CDUnknownBlockType)arg2;
- (void)endService;
- (void)beginService;
- (id)initInSilo:(id)arg1;
- (void)heartAttack;

@end

