//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface CMActivityAlarm : NSObject
{
    struct CLActivityAlarmConcentrator *fConcentrator;
    BOOL fIsValid;
    struct __CFRunLoop *fRunLoop;
    NSObject<OS_dispatch_queue> *fQueue;
    CDUnknownBlockType fHandler;
    unsigned int _trigger;
    NSString *_bundleId;
    NSString *_executable;
    double _duration;
}

+ (id)activityAlarmInfo;
+ (BOOL)activityAlarmAvailable;
@property(copy, nonatomic) NSString *executable; // @synthesize executable=_executable;
@property(copy, nonatomic) NSString *bundleId; // @synthesize bundleId=_bundleId;
@property(nonatomic) unsigned int trigger; // @synthesize trigger=_trigger;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void)fire;
- (BOOL)isValid;
- (void)invalidate;
- (void)dealloc;
- (id)initWithTrigger:(unsigned int)arg1 duration:(double)arg2 onRunLoop:(struct __CFRunLoop *)arg3 withHandler:(CDUnknownBlockType)arg4;
- (id)initWithTrigger:(unsigned int)arg1 duration:(double)arg2 onQueue:(id)arg3 forClient:(const struct Name *)arg4 withHandler:(CDUnknownBlockType)arg5;
- (id)initWithTrigger:(unsigned int)arg1 duration:(double)arg2 onQueue:(id)arg3 withHandler:(CDUnknownBlockType)arg4;

@end

