//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBRequest.h"

#import "NSCopying.h"

@class CRMeta, NSData, NSMutableArray;

@interface CRPassCollectionRequest : PBRequest <NSCopying>
{
    CRMeta *_meta;
    NSMutableArray *_passLocations;
    NSData *_signature;
}

@property(retain, nonatomic) NSData *signature; // @synthesize signature=_signature;
@property(retain, nonatomic) NSMutableArray *passLocations; // @synthesize passLocations=_passLocations;
@property(retain, nonatomic) CRMeta *meta; // @synthesize meta=_meta;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (Class)responseClass;
- (unsigned int)requestTypeCode;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) BOOL hasSignature;
- (id)passLocationAtIndex:(unsigned int)arg1;
- (unsigned int)passLocationsCount;
- (void)addPassLocation:(id)arg1;
- (void)clearPassLocations;
- (void)dealloc;

@end

