THEOS_DEVICE_IP = 127.0.0.1
THEOS_DEVICE_PORT = 2222
ARCHS = armv7
TARGET = iPhone:7.1

include theos/makefiles/common.mk

TWEAK_NAME = locationdtweak
locationdtweak_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk